name: 'Deploy to Dokku'

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: 'Deploy Pipeline'
    runs-on: ubuntu-latest

    # services:
    #     # Label used to access the service container
    #     redis:
    #       # Docker Hub image
    #       image: redis
    #       # Set health checks to wait until redis has started
    #       options: >-
    #         --health-cmd "redis-cli ping"
    #         --health-interval 2s
    #         --health-timeout 3s
    #         --health-retries 5
    steps:
      - uses: actions/checkout@v3

      # - name: Python Tests
      #   uses: tctree333/SciOlyID-Actions/python-tests@master
      #   env:
      #     SCIOLY_ID_BOT_LOCAL_REDIS: "true"
      #     SCIOLY_ID_BOT_LOCAL_REDIS_HOST: "redis"
      #     SCIOLY_ID_BOT_USE_SENTRY: "false"
      #     CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}

      - name: Sentry Deploys
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_INTEGRATION_TOKEN }}
          SENTRY_ORG: sciolyid
          SENTRY_PROJECT: bird-id-discord

      - name: Sentry Deploys
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_INTEGRATION_TOKEN }}
          SENTRY_ORG: sciolyid
          SENTRY_PROJECT: bird-id-api

      - name: Deploy to Dokku
        uses: tctree333/SciOlyID-Actions/deploy-dokku@master
        with:
          dokku app name: bird-id
          dokku host: ${{ secrets.DOKKU_HOST }}
          ssh private key: ${{ secrets.PRIVATE_KEY }}
